### ISSUE TITLE
About the “Pick pod selection rules decisions(PPS)” part in the code

### ISSUE THREAD

**Issue by xsingit** [merschformann/RAWSim-O#3]
Hello! Thanks for your great work! I think this work is very important and meaningful for studying decision problemss of RMFS. In this simulation framework, the POA and PPS decision problems are treated separately.
The some code description about POA optimizer is found in the “\RAWSimO.Core\Control\Defaults\OrderBatching”, however, I did not find the code description of PPS optimizer (including its several decision rules, such as "Pile-on","Demand",etc.,)  and did not understand how the PPS optimizer was called.
Any suggestion will be appreciated! Thanks.

**Comment by merschformann** [comment]
Hi!
I understand your confusion, since the code structure around task creation is a bit special. You can find the implementations for PPS and also RPS in `RAWSimO.Core.Control.BotManager` (File: _BotManagerPodSelection.cs_). Basically, the PPS and RPS mechanisms are sub-calls of the bot manager handling task creation & allocation in general.
Honestly, the implementation is quite odd in that part. I needed it to be quite flexible and I never had enough time to clean it up properly. However, I hope the regions in there at least give you some guidance.
The configuration for the implemented selectors is hosted within TaskAllocationConfig -> PodSelectionConfig. It is possible to configure multiple mechanisms together (first one is main, second one is first tie-breaker, third one is second tie-breaker). Simply replace one by pressing clear and then init a different one. The Output... ones are PPS and the Input... ones are RPS.
All implemented mechanisms are quite myopic / heuristic ones. If you want to implement a PPS mechanism of your own, you could start by looking at this one: [link](https://github.com/merschformann/RAWSim-O/blob/c94e69cc0de8479fe607cd55f21bc2f7d546b206/RAWSimO.Core/Control/BotManagerPodSelection.cs#L645).

I am very happy, if my work helps your projects! Let me know, if you have further questions.
You can also email me, if you don't want to share some project details openly.

I hope my answers above help you out a bit. :)
Have a great day!

**Comment by xsingit** [comment]
Thanks a lot! Your reply is very detailed and useful. I truly appreciate your timely help and look forward to having more communication with you in the future！Thanks again!

**Comment by merschformann** [comment]
No problem. I will close this then. :)
